baseURL = "https://www.gregdom.com/"
copyright = "© 2023 Greg Domzalski. All rights reserved."
languageCode = 'en-us'
title = 'Greg Domzalski'
titleCaseStyle = "none" # I'll take care of it myself, thank you.

enableEmoji = true
paginate = 3

[social]
linkedin = 'https://www.linkedin.com/in/gregdomzalski'
github = 'https://github.com/GregDomzalski'
twitter = 'https://twitter.com/#'

[params]
  [params.author]
    name = 'Greg Domzalski'
    email = 'blog at gregdom dot com'
  bio = 'Staff Software Engineer @ Yubico'

[outputs]
  home = ['html']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']

[services]
  [services.rss]
    limit = 10

[menu]
  [[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 100

  [[menu.main]]
    name = "Blog"
    pageRef = "/posts"
    weight = 200

  ## Projects
  [[menu.main]]
    name = "Projects"
    pageRef = '/projects'
    weight = 300

  [[menu.main]]
    name = "GeNet"
    parent = "Projects"
    url = "https://github.com/GregDomzalski/GeNet"
    weight = 10
    [menu.main.params]
      rel = "external"
      target = "_blank"

  [[menu.main]]
    name = "Refraction"
    parent = "Projects"
    url = "https://github.com/GregDomzalski/Refraction"
    weight = 20
    [menu.main.params]
      rel = "external"
      target = "_blank"

  [[menu.main]]
    name = "BinForge"
    parent = "Projects"
    url = "https://github.com/GregDomzalski/BinForge"
    weight = 30
    [menu.main.params]
      rel = "external"
      target = "_blank"
      
  [[menu.main]]
    name = "PowerShell Utils"
    parent = "Projects"
    pageRef = "/projects/PowerShell"
    weight = 40

  [[menu.main]]
    name = "DotFiles"
    parent = "Projects"
    url = "https://github.com/GregDomzalski/dotfiles"
    weight = 50
    [menu.main.params]
      rel = "external"
      target = "_blank"

  ## Books
  [[menu.main]]
    name = "Books"
    pageRef = "/books"
    weight = 400

  [[menu.main]]
    name = ".NET Esoterica"
    parent = "Books"
    pageRef = "/books/dotnet-esoterica"
    weight = 10

  [[menu.main]]
    name = "Homelab How-to"
    parent = "Books"
    pageRef = "/books/homelab"


  ## About me
  [[menu.main]]
    name = 'About me'
    pageRef = '/about'
    weight = 500

  [[menu.main]]
    name = "CV"
    parent = "About me"
    pageRef = "/about/cv"
    weight = 10

  [[menu.main]]
    name = "Things I use"
    parent = "About me"
    pageRef = "/about/uses"
    weight = 20

  [[menu.main]]
    name = "Things I want"
    parent = "About me"
    pageRef = "/about/wants"
    weight = 30

  [[menu.main]]
    name = "Contact"
    parent = "About me"
    pageRef = "/contact"
    weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min      = "0.112.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"
