baseURL = 'http://GregDomzalski.github.io/'
languageCode = 'en-us'
title = 'Greg Domzalski'
# theme = 'mini' # Still requiring layout for page, taxonomy, and section
paginate = 3

[social]
linkedin = 'https://www.linkedin.com/in/gregdomzalski'
github = 'https://github.com/GregDomzalski'
twitter = 'https://twitter.com/#'

[params]
author = 'Greg Domzalski'
bio = 'Staff Software Engineer @ Yubico'
description = 'My Blog'
enableRSS = true
enableComments = false
enableGoogleAnalytics = false

[menu]
[[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
[[menu.main]]
    name = 'CV'
    pageRef = '/cv'
    weight = 20
[[menu.main]]
    name = 'Blog'
    pageRef = '/posts'
    weight = 30
[[menu.main]]
    name = 'Things I use'
    pageRef = '/uses'
    weight = 40
[[menu.main]]
    name = 'Books'
    pageRef = '/books'
    weight = 50
[[menu.main]]
    name = 'Contact'
    pageRef = '/contact'
    weight = 60

[module]
  [module.hugoVersion]
    extended = false
    min      = "0.112.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"