baseURL = 'https://www.gregdom.com/'
languageCode = 'en-us'
title = 'Greg Domzalski'
paginate = 3

[social]
linkedin = 'https://www.linkedin.com/in/gregdomzalski'
github = 'https://github.com/GregDomzalski'
twitter = 'https://twitter.com/#'

[params]
author = 'Greg Domzalski'
bio = 'Staff Software Engineer @ Yubico'
description = 'My Blog'
enableRSS = true
enableComments = false
enableGoogleAnalytics = false

# Home
# Blog
# Projects
# - GeNet
# - Refraction
# - BinForge
# - PowerShell Utilities
# - DotFiles
# About me
# - CV
# - Things I use
# - Contact

[menu]
  [[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 100

  [[menu.main]]
    name = "Blog"
    pageRef = "/posts"
    weight = 200

  ## Projects
  [[menu.main]]
    name = "Projects"
    pageRef = '/projects'
    weight = 300

  [[menu.main]]
    name = "GeNet"
    parent = "Projects"
    pageRef = "/projects/GeNet"
    weight = 10
  [[menu.main]]
    name = "Refraction"
    parent = "Projects"
    pageRef = "/projects/Refraction"
    weight = 20
  [[menu.main]]
    name = "BinForge"
    parent = "Projects"
    pageRef = "/projects/BinForge"
    weight = 30
  [[menu.main]]
    name = "PowerShell Utils"
    parent = "Projects"
    pageRef = "/projects/PowerShell"
    weight = 40
  [[menu.main]]
    name = "DotFiles"
    parent = "Projects"
    pageRef = "/projects/DotFiles"
    weight = 50

  ## About me
  [[menu.main]]
    name = 'About me'
    pageRef = '/about'
    weight = 400

  [[menu.main]]
    name = "CV"
    parent = "About me"
    pageRef = "/about/cv"
    weight = 10
  [[menu.main]]
    name = 'Things I use'
    parent = "About me"
    pageRef = '/about/uses'
    weight = 20
  [[menu.main]]
    name = 'Contact'
    parent = "About me"
    pageRef = '/contact'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min      = "0.112.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"