direction: right

MemberDeclarationSyntax
MemberDeclarationSyntax -> BaseFieldDeclarationSyntax
MemberDeclarationSyntax -> BaseMethodDeclarationSyntax
MemberDeclarationSyntax -> BaseNamespaceDeclarationSyntax
MemberDeclarationSyntax -> BasePropertyDeclarationSyntax
MemberDeclarationSyntax -> BaseTypeDeclarationSyntax