direction: up

BaseMethodDeclarationSyntax -> MemberDeclarationSyntax
ConstructorDeclarationSyntax -> BaseMethodDeclarationSyntax
ConversionOperatorDeclarationSyntax -> BaseMethodDeclarationSyntax
DestructorDeclarationSyntax -> BaseMethodDeclarationSyntax
MethodDeclarationSyntax -> BaseMethodDeclarationSyntax
OperatorDeclarationSyntax -> BaseMethodDeclarationSyntax