direction: up

BaseNamespaceDeclarationSyntax -> MemberDeclarationSyntax
FileScopedNamespaceDeclarationSyntax -> BaseNamespaceDeclarationSyntax
NamespaceDeclarationSyntax -> BaseNamespaceDeclarationSyntax