direction: up

BasePropertyDeclarationSyntax -> MemberDeclarationSyntax
EventDeclarationSyntax -> BasePropertyDeclarationSyntax
IndexerDeclarationSyntax -> BasePropertyDeclarationSyntax
PropertyDeclarationSyntax -> BasePropertyDeclarationSyntax