direction: up

BaseTypeDeclarationSyntax -> MemberDeclarationSyntax

EnumDeclarationSyntax -> BaseTypeDeclarationSyntax
TypeDeclarationSyntax -> BaseTypeDeclarationSyntax

ClassDeclarationSyntax -> TypeDeclarationSyntax
InterfaceDeclarationSyntax -> TypeDeclarationSyntax
RecordDeclarationSyntax -> TypeDeclarationSyntax
StructDeclarationSyntax -> TypeDeclarationSyntax